apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: only_template
  name: no-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: only_template
  template:
    metadata:
      labels:
        app: only_template
    spec:
      # serviceAccountName: dev-xx-role
      containers:
      - image: monopole/hello:1
        name: no-container
        command: [/bin/bash, -c, 'sleep infinity']
        # command: ["/hello",
        #           "--port=8080",
        #           "--enableRiskyFeature=$(ENABLE_RISKY)"]
        env:
          - name: env1
            value: xx        
        ports:
        - containerPort: 8080
        # env:
        # - name: ALT_GREETING
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: altGreeting
        # - name: ENABLE_RISKY
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: enableRisky