apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      only_template: hello
  template:
    metadata:
      labels:
        only_template: hello
    spec:
      containers:
      - name: no-container
        image: monopole/hello:1
        command: [/bin/bash, -c, 'sleep infinity']
        # command: ["/hello",
        #           "--port=8080",
        #           "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 8080
        # env:
        # - name: ALT_GREETING
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: altGreeting
        # - name: ENABLE_RISKY
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: enableRisky