apiVersion: v1
kind: Service
metadata:
  labels:
    app: only_template  
  name: no-service
spec:
  selector:
    app: only_template
  # type: LoadBalancer
  ports:
  - port: 6666
    targetPort: 8080
    protocol: TCP